# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
