# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20170310_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
