# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_members_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
