# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20170310_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
