# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-13 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_members_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
