# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
