# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20170313_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
