# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20170324_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
    ]
