# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-22 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_bench', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlbench',
            options={'verbose_name': 'Url Bench', 'verbose_name_plural': 'Url Bench'},
        ),
    ]
