# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_auto_20170310_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 10, 18, 20, 24, 591422, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
