# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_auto_20170310_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprints',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sprints',
            name='team',
        ),
    ]
