# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_auto_20170310_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
