# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0006_auto_20170311_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sprints',
            options={'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
    ]
