# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20170324_0642'),
        ('sprints', '0007_auto_20170324_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(default=None, max_length=50)),
                ('ticket_desc', models.CharField(default=None, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default=None, max_length=50)),
                ('comments', models.CharField(default=None, max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Members')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprints')),
            ],
            options={
                'verbose_name': 'Sprint Summary',
                'verbose_name_plural': 'Sprint Summary',
            },
        ),
    ]
