# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0008_sprintsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintsummary',
            name='sprint',
        ),
        migrations.AddField(
            model_name='sprintsummary',
            name='sprint_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sprintsummary',
            name='member',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sprintsummary',
            name='ticket_desc',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
