# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0009_auto_20170328_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintsummary',
            name='sprint_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
