# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0011_auto_20170328_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintsummary',
            name='due_date',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
