# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0012_auto_20170328_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintsummary',
            name='comments',
        ),
    ]
