# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0013_remove_sprintsummary_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsummary',
            name='issue_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
