# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0014_sprintsummary_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintsummary',
            name='reporter',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
