# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprints')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(default=None, max_length=50)),
                ('parameter', models.IntegerField(choices=[(1, 'Idea'), (2, 'Enthu'), (3, 'Quality'), (4, 'Quantum')], default=None)),
                ('comments', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Booth')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Members')),
            ],
        ),
    ]
