# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='comments',
            field=models.TextField(max_length=200),
        ),
    ]
