# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20170311_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='booth_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
