# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20170312_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booth',
            options={'verbose_name': 'Booth', 'verbose_name_plural': 'Booth'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterModelOptions(
            name='votingparams',
            options={'verbose_name': 'Voting Param', 'verbose_name_plural': 'Voting Params'},
        ),
    ]
