# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20170426_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingparams',
            name='comments',
            field=models.TextField(max_length=1500),
        ),
    ]
