# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_remove_members_age'),
        ('sprints', '0016_auto_20170422_1824'),
        ('voting', '0010_auto_20170426_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Members')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprints')),
            ],
            options={
                'verbose_name': 'Vote Summary',
                'verbose_name_plural': 'Vote Summary',
            },
        ),
    ]
