# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_remove_members_age'),
        ('voting', '0011_votesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField()),
                ('current_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Members')),
            ],
        ),
    ]
