# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_quartersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='quarter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.QuarterSummary'),
        ),
    ]
