# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20170510_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartersummary',
            options={'verbose_name': 'Quarter Summary', 'verbose_name_plural': 'Quarter Summary'},
        ),
        migrations.AlterField(
            model_name='quartersummary',
            name='total_votes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
