# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20170510_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartersummary',
            name='current_winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Members'),
        ),
    ]
