# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20170510_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartersummary',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
