# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprints', '0007_auto_20170324_0642'),
        ('teams', '0013_auto_20170324_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Members')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprints')),
            ],
            options={
                'verbose_name': 'Activity Board',
            },
        ),
    ]
