# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityboard',
            options={'verbose_name': 'Activity Board', 'verbose_name_plural': 'Activity Board'},
        ),
        migrations.AlterField(
            model_name='activityboard',
            name='remark',
            field=models.TextField(max_length=200),
        ),
    ]
